### ISSUE TITLE
Add import test to the supported resources

### ISSUE THREAD

**Issue by blackjid** [platanus/terraform-provider-rancher#11]
We should add some tests to the resources that support import. Like in https://github.com/platanus/terraform-provider-rancher/blob/master/rancher/import_rancher_environment_test.go

cc: @raphink

**Comment by raphink** [comment]
I'm not actually sure what import does. What is it for?

**Comment by blackjid** [comment]
if you already have an environment or resource running, deployed manually.. you can declare the resource in terraform and then import it's state.

```
resource "rancher_environment" "default" {
  name = "staging"
  description = "The staging environment"
  orchestration = "cattle"
}
```

`terraform import racher_environment.default 1a5`

After that if you run `terraform plan` it shouldn't need to create the resource because it's already there and was imported

**Comment by raphink** [comment]
Ah nice! So this replaces https://github.com/dtan4/terraforming natively then!
