### ISSUE TITLE
v0.2.0 binaries not built on v0.2.0

### ISSUE THREAD

**Issue by mcanevet** [platanus/terraform-provider-rancher#17]
Hello,
When using the binaries available with the release, I still have to use `CATTLE_*` environment variables, which makes me think that they are not build towards v0.2.0...

**Comment by blackjid** [comment]
I'll take a look

are the new resources available??

**Comment by blackjid** [comment]
@mcanevet I just tried it and it's working fine with the released binaries (at least darwin amd64)
Make sure you don't have the older version somewhere in the path that might be taking precedence.

**Comment by mcanevet** [comment]
@blackjid I'm using linux64 binaries. The new resources are available. It looks like it is built with the commit just before f44fdb3.

**Comment by blackjid** [comment]
that's weird... I just tried on a linux machine with the linux64 builds and I need to pass the `RANCHER_*` variables

**Comment by mcanevet** [comment]
weird indeed...
I must have done something wrong on my side. I close this.
Thanks

**Comment by blackjid** [comment]
👍
