### ISSUE TITLE
add catalog resource

### ISSUE THREAD

**Issue by justmiles** [platanus/terraform-provider-rancher#18]
Rancher allows you to add custom catalogs as git repos. It would be nice to provision those catalogs with terraform.

**Comment by blackjid** [comment]
we are not going to continue development in this plugin since the code base was merged to terraform. Please open an issue on terraform repo itself...

https://github.com/platanus/terraform-provider-rancher/commit/9c77f7972071e1ed76d3d99e64b7b36c26c3a7ee

thanks
