### ISSUE TITLE
Unable to remove vars

### ISSUE THREAD

**Issue by Vampouille** [platanus/terraform-provider-rancher#19]
I remove some variables from my stack.tf file but terraform was unable to remove those variables on rancher: a terraform apply always show differences about variables count : 

```
rancher_stack.georchestra-apache-nas: Modifying...
  environment.%:            "6" => "1"
  ...
  ...
```

**Comment by blackjid** [comment]
Could you please test that with the official integration since terraform 0.8?? And open the issue on https://github.com/hashicorp/terraform if necessary?

https://github.com/platanus/terraform-provider-rancher/commit/9c77f7972071e1ed76d3d99e64b7b36c26c3a7ee

**Comment by blackjid** [comment]
thanks...
