### ISSUE TITLE
Add support for timeout options

### ISSUE THREAD

**Issue by Vampouille** [platanus/terraform-provider-rancher#20]
Currently timeout is not supported by rancher provider. Can you add support for `timeouts` option or increase default timeout to 20 min ?

I try to add following block to a `rancher_stack` resource:

```hcl
  timeouts {                                                                                                                           
    create = "20m"
    delete = "20m"
  } 
```

```
[ERR] Error decoding timeout: Timeout Key (create) is not supported
```

**Comment by blackjid** [comment]
hi, sorry but we are not actively developing this provider since it was included in terraform.
you should use the official provider and maybe create an issue in that repo https://github.com/terraform-providers/terraform-provider-rancher
