### ISSUE TITLE
Change Environmental Variables to RANCHER_

### ISSUE THREAD

**Issue by blackjid** [platanus/terraform-provider-rancher#9]
For the access key and secret, I think it makes more sense that the environmental variables would be:
- `RANCHER_ACCESS_KEY`
- `RANCHER_ACCESS_SECRET`
- `RANCHER_URL`

Now the variables are prefixed with `CATTLE` wich is the orchestration engine withing rancher... so `RANCHER_` would be easier to understand and more intuitive.

@raphink what do you think?

**Comment by raphink** [comment]
In my provider, I had used the RANCHER variables. There is a difference though: CATTLE_URL = RANCHER _URL + "/v1"

**Comment by raphink** [comment]
In the end, I'd prefer to use a config file with profiles, as explained in #7

**Comment by blackjid** [comment]
I think I prefer the abstract the complete url... so the user doen't need to know which version in the url...  The provider should use whatever version is supported...

**Comment by raphink** [comment]
In that case, RANCHER _URL is a better choice.
